Earthquakes (scaled)
concord-consortium/geocode pull request #256
Opened 2021-08-24 16:08 UTC by sfentress

This adds some scaling options to the model, such that the model author can pretend the width of the model is different from what it actually is, and the time scale is different.

One way to play with it is to set up a model such as in #255, run it, and then after it has run change

* The actual width of the model
* The apparent width of the mode
* The apparent year scaling

The first option will change the curvature of the lines and the shape of the triangle, as the actual simulation will have been run closer to or further from the fault line. The second two options will only change the scale label and the year label.

The year scaling will also come into play when users can step through the model year by year in code.

This also adds the ability to hide the year label altogether.

https://geocode-app.concord.org/branch/earthquakes-scaled/index.html

2021-08-31 17:47 UTC, mklewandowski commented
@sfentress are we off by a factor of 10 in the apparent width that is in the authoring and displayed in the deformation model?
![image](https://user-images.githubusercontent.com/5126913/131551263-6e9c7411-4764-4fbb-a621-0b114f63931b.png)

2021-08-31 17:50 UTC, mklewandowski requested changes
Looks good.  I'm still trying to wrap my head around what exactly the model width authoring control does, but I think I'm starting to get it.  The only issue that I noticed is that the apparent width setting in the authoring doesn't seem to match the apparent width shown on the deformation model.

2021-09-01 14:23 UTC, sfentress commented
@mklewandowski The scale marker is like a map's scale marker: the distance is from one end of the line to the other. The line is a tenth of the width of the model, and shows a tenth of the apparent width you selected.

If I'm being dense and missing what you're saying, LMK. Otherwise I *think* this is fine, and will bring it in.

2021-09-01 14:23 UTC, merged

2021-09-01 14:56 UTC, mklewandowski commented
Got it.  My confusion.